name: Parkour
version: "1.2"
author: jdcraft
api: [2.0.0, 3.0.0-ALPHA1]
main: jdcraft\parkour\Main

permissions:
 parkour.*:
  description: all permissions for parkour
  children:
   parkour.create:
    description: Allows player to make and break their own parkours

commands:
 pk:
  description: Parkour Commands