name: Parkour
version: 1.5.6-2
author: awzaw
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9]
main: awzaw\parkour\Main

permissions:
 parkour.*:
  description: all permissions for parkour
  children:
   parkour.create:
    description: Allows player to make and break their own parkours
commands:
 pk:
  description: Parkour Commands